# Generated by Django 3.1.8 on 2021-10-26 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_program', '0005_auto_20211026_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='discount_code_list',
        ),
        migrations.AddField(
            model_name='follower',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loyalty_program.discountcode'),
        ),
    ]
